#!/bin/bash

labo_setup_main(){
  labo_setup_shared
  labo_setup_config
}
labo_setup_shared(){
  local path

  cd $HOME
  if [ -d .shared ]; then
    for path in $(ls -a1 .shared); do
      case "$path" in
        .|..)
          ;;
        *)
          if [ ! -L $path ]; then
            if [ -e $path ]; then
              echo "$path exists. not linked"
            else
              echo "ln -s .shared/$path"
              ln -s .shared/$path
            fi
          fi
          ;;
      esac
    done
  fi
}
labo_setup_config(){
  local rc
  rc=$HOME/.config/rc

  if [ -x "$rc" ]; then
    $rc
  fi
}

labo_setup_main
