#!/bin/bash

labo_setup_main(){
  local root
  root=$HOME

  labo_setup_shared
  labo_setup_config
}

labo_setup_shared(){
  local path

  cd $root
  if [ -d .shared ]; then
    for path in $(ls -a1 .shared); do
      case "$path" in
        .|..)
          ;;
        *)
          if [ ! -L $path ]; then
            if [ -e $path ]; then
              echo "$path exists. not linked"
            else
              echo "ln -s .shared/$path"
              ln -s .shared/$path
            fi
          fi
          ;;
      esac
    done
  fi
}

labo_setup_config(){
  cd $root
  labo_setup_config_link .config/tmux/config .tmux.conf
  labo_setup_config_link .config/zsh/zshrc .zshrc
  labo_setup_config_link .config/git/config .gitconfig
}
labo_setup_config_link(){
  if [ ! -L $2 ]; then
    echo "ln -s $1 $2"
    ln -s $1 $2
  fi
}

labo_setup_main
